# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "bento/ubuntu-16.04"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.network "private_network", ip: "192.168.50.12"
  config.vm.hostname = "master.example.com"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # disable the default root
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.
  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 2
    v.name = "puppet_master"
  end

  # Define a Vagrant Push strategy for pushing to Atlas. Other push strategies
  # such as FTP and Heroku are also available. See the documentation at
  # https://docs.vagrantup.com/v2/push/atlas.html for more information.
  # config.push.define "atlas" do |push|
  #   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
  # end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
  config.vm.provision "file", source: "./pe.conf", destination: "/var/tmp/pe.conf"
  #config.vm.provision "file", source: "./puppet-enterprise.tar.gz", destination: "/var/tmp/puppet-enterprise.tar.gz"
  config.vm.provision "file", source: "./id-puppet_control_repo.rsa", destination: "/var/tmp/id-puppet_control_repo.rsa"

  config.vm.provision "shell", privileged: false, inline: <<-SHELL

  	########################
    # Packages and Sources #
    ########################
    # Packages update and upgrade
    sudo apt-get update
    sudo DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" upgrade
  	# Puppet Enterprise (For URL, see https://puppet.com/download-puppet-enterprise/thank-you)
    echo "--- Get puppet enterprise (it can take a while... ~250Mo)."
  	wget --no-verbose -cO /var/tmp/puppet-enterprise.tar.gz 'https://pm.puppetlabs.com/cgi-bin/download.cgi?dist=ubuntu&rel=16.04&arch=amd64&ver=latest'
  	tar -xf /var/tmp/puppet-enterprise.tar.gz -C /var/tmp/ --transform "s/puppet-enterprise-[0-9\.]*-ubuntu-16.04-amd64/puppet-enterprise/"
  	sudo /var/tmp/puppet-enterprise/puppet-enterprise-installer -c /var/tmp/pe.conf
  	# Move the private key
  	sudo mkdir /etc/puppetlabs/puppetserver/ssh
  	sudo mv /var/tmp/id-puppet_control_repo.rsa /etc/puppetlabs/puppetserver/ssh/id-puppet_control_repo.rsa

  SHELL

  # The following provisions are only run when called explicitly
  if ARGV.include? '--provision-with'

    # Provision "sign-cert"
    config.vm.provision "sign-cert", type: "shell", privileged: false, inline: <<-SHELL
      sudo puppet cert sign --all
    SHELL

    # Provision "restart-services"
    # Restart the puppet console services
    # https://tickets.puppetlabs.com/browse/LEARNVM-387
    config.vm.provision "restart-services", type: "shell", privileged: true, inline: <<-SHELL
      service pe-puppetdb stop
      service pe-puppetserver stop
      service pe-console-services stop
      # puppetdb foreground
      service pe-puppetdb start
      service pe-puppetserver start
      service pe-console-services start
    SHELL

    # Provision "clean-agent-cert"
    # See https://puppet.com/docs/pe/2017.3/ssl_and_certificates/regenerate_puppet_agent_certificates.html
    config.vm.provision "clean-agent-cert", type: "shell", privileged: true, inline: <<-SHELL
      puppet cert clean agent1.example.com
    SHELL

    # Provision "clean-master-cert"
    # See https://puppet.com/docs/pe/2017.3/ssl_and_certificates/regenerating_certificates_monolithic_installs.html
    config.vm.provision "clean-master-cert", type: "shell", privileged: true, inline: <<-SHELL
      # Back up the directory
      DATE=$(date +"%d-%b-%Y")
      cd /etc/puppetlabs/puppet
      tar -zcvf ssl-$DATE.tgz ssl
      # (Optional) Delete and recreate the Puppet CA
        # rm -rf /etc/puppetlabs/puppet/ssl/*
        # puppet cert list -a
      # Regenerate the Puppet master certificates
      rm -f /opt/puppetlabs/puppet/cache/client_data/catalog/master.example.com.json
      puppet cert clean master.example.com
      puppet infrastructure configure --no-recover
    SHELL

    # Provision "manage_code"
    # See https://puppet.com/docs/pe/2017.3/code_management/code_mgr_config.html
    config.vm.provision "manage_code", type: "shell", privileged: true, inline: <<-SHELL
      echo "This provision is not done yet..."
      echo "See https://puppet.com/docs/pe/2017.3/code_management/code_mgr_config.html#set-up-authentication-for-code-manager"
      #puppet module install puppetlabs-stdlib
      #puppet apply -e "user { 'code_manager': ensure => present, roles => 'Code Deployers', password => str2saltedsha512('code_manager') }"
      #puppet-access login --lifetime 180d
      #puppet-code deploy production --wait
    SHELL

  end

end
